import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import alias from 'esbuild-plugin-alias';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// Node built-ins under both spellings (`stream` and `node:stream`).
		...builtinModules.flatMap((m) => (m.startsWith('node:') ? [m] : [m, `node:${m}`])),
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	// Inline sourcemaps embed the full source of every dep as base64. In dev
	// (watch mode) they're worth ~5–7× the binary size for the debugger; in
	// prod the shipped artifact stays minified (line numbers map back to the
	// repo source). Without this guard, main.js ships at ~11 MB and exceeds
	// the Obsidian Sync Standard 5 MB threshold.
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		alias({
			'@': path.resolve(__dirname, 'src'),
		}),
	],
	loader: {
		'.hbs': 'text',
		'.json': 'json',
		'.md': 'text',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
