import { getLanguage } from 'obsidian';
import { en, type TranslationKey } from './en';
import { cs } from './cs';
import { da } from './da';
import { de } from './de';
import { es } from './es';
import { fr } from './fr';
import { id } from './id';
import { it } from './it';
import { ja } from './ja';
import { ko } from './ko';
import { nl } from './nl';
import { no } from './no';
import { pl } from './pl';
import { pt } from './pt';
import { ptBR } from './pt-br';
import { ru } from './ru';
import { tr } from './tr';
import { uk } from './uk';
import { vi } from './vi';
import { zh } from './zh';
import { zhTW } from './zh-tw';

export type { TranslationKey };

/**
 * All shipped translation tables, keyed by Obsidian locale code.
 * Language files are AI-generated by `npm run translate` (scripts/translate.mjs) and committed;
 * hand-refinements survive regeneration (see translation-state.json).
 *
 * Exported so tests can verify registry/file parity.
 */
export const locales: Record<string, Partial<Record<TranslationKey, string>>> = {
	cs,
	da,
	de,
	es,
	fr,
	id,
	it,
	ja,
	ko,
	nl,
	no,
	pl,
	pt,
	'pt-BR': ptBR,
	ru,
	tr,
	uk,
	vi,
	zh,
	'zh-TW': zhTW,
};

/**
 * Resolve Obsidian's UI language to a shipped locale: exact match ('zh-TW'),
 * else base language ('fr-CA' → 'fr'), else 'en'.
 */
export function getResolvedLocale(): string {
	const raw = getLanguage() || 'en';
	if (raw === 'en' || locales[raw]) {
		return locales[raw] ? raw : 'en';
	}
	const base = raw.split('-')[0];
	return locales[base] ? base : 'en';
}

/**
 * Translate a UI string. Falls back to English for missing or empty translations.
 * `vars` fills `{name}`-style placeholders; unknown placeholders are left intact.
 */
export function t(key: TranslationKey, vars?: Record<string, string | number>): string {
	const locale = getResolvedLocale();
	const translated = locale === 'en' ? undefined : locales[locale]?.[key];
	const msg = translated && translated.trim() !== '' ? translated : en[key].message;
	if (!vars) {
		return msg;
	}
	return msg.replace(/\{(\w+)\}/g, (match, name: string) => (name in vars ? String(vars[name]) : match));
}
